### ISSUE TITLE
현재 사용중인 포트 식별 요청

### ISSUE THREAD

**Issue by BANDI-Plan** [MECTrace/edge-node#1]
현재 인바운드규칙에 8888 Port가 추가되어 있습니다.
해당 포트 사용 목적 확인이 필요합니다.

**Comment by choiysr** [comment]
> 현재 인바운드규칙에 8888 Port가 추가되어 있습니다. 해당 포트 사용 목적 확인이 필요합니다.

기존 8443 Port와 동일한 역할의 애플리케이션으로 V&V Test용으로 사용하기 위해 분리했습니다.
